#ifndef GRAFICOS_3D_ESCENARIOS_ESCENARIO_VERSUS_H__
#define GRAFICOS_3D_ESCENARIOS_ESCENARIO_VERSUS_H__

void Dibujar_Escenario_Versus_J1(void);
void Dibujar_Escenario_Versus_J2(void);

#endif // GRAFICOS_3D_ESCENARIOS_ESCENARIO_VERSUS_H__
